### ISSUE TITLE
802.1CB 2 Board

### ISSUE THREAD

**Issue by jman-88** [vladimiroltean/tsn-scripts#1]
Will there be an update to the `8021cb-2boards` branch? I am trying to do a CB test with two LS1028A-RDB boards, but I can't get it going by modifying the `8021cb-devel` branch.

**Comment by vladimiroltean** [comment]
On Thu, Sep 03, 2020 at 12:08:39AM -0700, JMan wrote:
> Will there be an update to the `8021cb-2boards` branch? I am trying to
> do a CB test with two LS1028A-RDB boards, but I can't get it going by
> modifying the `8021cb-devel` branch.

What do you need to modify?
You should be able to just use the json files for board1 and board2 from
the 8021cb-devel branch, and disregard the third. The connection would
go from board2 swp0 to board1 swp1 and from board2 swp1 to board1 swp0.
What is the issue you're facing when trying to do that?

Thanks,
-Vladimir

**Comment by vladimiroltean** [comment]
> The only change I made was to remove linuxptp as it was failing to compile.

wow, this doesn't sound very nice.
Let me build the openil master branch and double-check if it works.

**Comment by vladimiroltean** [comment]
So first of all, the linuxptp package built successfully right now, with the master branch at https://github.com/openil/openil/commit/65d832a2ef1479ee5a51e6990a5fcb61ff3dc71f. Could you share an error log?

**Comment by vladimiroltean** [comment]
Ok, so there was indeed a recently introduced incompatibility between the return code of a tsntool command, and what this script expected. I fixed it in here: https://github.com/vladimiroltean/tsn-scripts/commit/6e0e291b1df82613a6a3e9cd358682ad2f78d8cd
I could ping fine with that 1-line change.
Could you please give it another go?

**Comment by jman-88** [comment]
I did a fresh build on a different machine with master. Basically I get two different issues with the build. First I encounter `multiple definition of 'yylloc'` during various times of the build. I managed to circumvent this. Then the PTP build issue. I think the PTP build might be looking for the header files on my system and not inside buildroot, but this is just a guess. I attached some logs for you.

[uboot.txt](https://github.com/vladimiroltean/tsn-scripts/files/5217321/uboot.txt)
[host-dtc.txt](https://github.com/vladimiroltean/tsn-scripts/files/5217318/host-dtc.txt)
[linux.txt](https://github.com/vladimiroltean/tsn-scripts/files/5217319/linux.txt)
[ptp.txt](https://github.com/vladimiroltean/tsn-scripts/files/5217320/ptp.txt)

The update to the tsn-scripts worked, but when I run iperf and disconnect the swp1 -> swp0 cable, the stream dies. When I disconnect swp0 -> swp1 the stream is fine. It appears that something is still missing. Do you get the same?

**Comment by vladimiroltean** [comment]
Yes, you are correct. I have fixed that. Please re-update the list of kernel patches and try again, it should work fine this time.
I will send these patches to OpenIL as soon as possible.

I didn't unfortunately have time to study your compilation issues. What host distribution are you using?

**Comment by jman-88** [comment]
Great. It is working now, but I'm observing some strange behavior. As I understand, I should be able to disconnect either swp0 or swp1 and the stream should not be interrupted as longs as one cable is connected. I observe the following:

- I start iperf3 to run indefinitely.
- Disconnect and reconnect the same port multiple times and the stream will eventually stop, unless both are connected. If I disconnect the other port and reconnect, then I can again disconnect and reconnect the initial port. Eventually it will stop again.
- I disconnect and reconnect swp0 and then swp1. If I repeat this the stream will eventually break.

Is this expected behavior or am I misunderstanding what CB should be able to do?

I'm on Manjaro Linux.

**Comment by vladimiroltean** [comment]
Have you updated _all_ Linux kernel patches?
What if you use ping instead of iperf3, do you ever run into this problem?
Have you looked at the patches in detail, this one especially?
```
Subject: [PATCH 2/2] net: dsa: felix: implement port flushing on
 .phylink_mac_link_down

Especially with flow control enabled on both the user port and the CPU
port, it may happen when a link goes down that Ethernet packets are in
flight. In flow control mode, frames are held back and not dropped. When
there is enough traffic in flight (example: iperf3 TCP), then the
ingress port might enter congestion and never exit that state. This is a
problem, because it is the egress port's link that went down, and that
has caused the inability of the ingress port to send packets to any
other port.

The solution is to follow the port flushing procedure from the reference
manual. This ensures that upon detection of link loss, the existing
packets are thrown away and congestion on the ingress port is therefore
avoided.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
```
Is this what's going on, I wonder? If you run `ethtool -S swp4 | grep pause` after iperf3 freezes, what do you see? By any chance, has the port entered congestion and it keeps sending PAUSE frames to ENETC?

**Comment by vladimiroltean** [comment]
> I'm on Manjaro Linux.

I don't think OpenIL gets build-tested on that, sorry.

**Comment by jman-88** [comment]
> Have you updated all Linux kernel patches?

Yes. I copied those in, removed `output-ls1028ardb/build/linux-linux-5.4.y` and built again.

> What if you use ping instead of iperf3, do you ever run into this problem?

I tested with ping now and did not manage to replicate the problem.

> Have you looked at the patches in detail, this one especially?

I did not look at it before, but this is probably it. I tested now and when the setup fails and I stop iperf, the `tx_pause` counter keeps on increasing. When I reconnect the cable, the `tx_pause` counter stops.

**Comment by vladimiroltean** [comment]
:(
So it looks like I'm missing a case when I need to flush the packets on the egress port when its link goes down.
Sorry, I have some other things I need to focus on right now, I'll come back to it at some point.
To work around this issue, you can edit this patch:
https://github.com/vladimiroltean/tsn-scripts/blob/8021cb-devel/deps/patches/linux/0001-arm64-dts-fsl-ls1028a-rdb-enable-swp5-and-move-NPI-p.patch
and remove the "pause" properties from the fixed-link node of the ENETC and of the Felix switch. This will disable flow control on the eno2 <-> swp4 port pair, which in turn will mean that the packets are no longer buffered by the switch when the link falls, but will be dropped instead. Be warned though, the iperf3 throughput without flow control will be worse.

**Comment by jman-88** [comment]
Okay. Thanks for the assistance. As long as there is a work around it is fine for now. Should I close this issue or keep it open?

**Comment by vladimiroltean** [comment]
Let me know if you see the lockups any longer with flow control disabled, and if that confirms my suspicion, you can close it and I'll return to this issue in a few days anyway. I'm trying to upstream the packet flushing logic and will make sure it works properly when I do that. How many times do you need to plug/unplug the cable? For me it worked 3-4 times, haven't tested further.

**Comment by jman-88** [comment]
> How many times do you need to plug/unplug the cable?

Sometimes it will break on the first disconnect, but it takes longer usually so it's a bit random. I was probably up to 20 plug/unplugs once before it happened.

I'll test the work around and let you know.

**Comment by jman-88** [comment]
With the work around I'm getting the same behavior. I double checked the device tree changes and `ethtool -S swp4 | grep pause` yields 0 and I can see decreased throughput with iperf. Will probably be good if someone else can confirm this.

I'll get back to this at some point as I have other things to deal with. I'll keep this open in case I forget.

**Comment by vladimiroltean** [comment]
Ok, so it isn't completely what I thought. I'll try to come back at it and see what's going on. Keep the ticket open, sure.

**Comment by vladimiroltean** [comment]
What ethtool counter is increasing now, if not tx_pause, though? Where are the packets dropped?

**Comment by jman-88** [comment]
That is a good question because I did not see anything funny going on with the counters of swp4 when the stream breaks.

**Comment by vladimiroltean** [comment]
So there are actually 6 places to check.
- tcpdump and ethtool on eno2
- ethtool on swp4
- ethtool on the egress ports (swp0 and swp1)
- ethtool on the ingress ports of the other board (swp0 and/or swp1)
- ethtool on swp4 of the other board
- tcpdump and ethtool on eno2 of the other board
Packets must be dropped somewhere, right?

**Comment by jman-88** [comment]
The port activity LEDs stop flashing when it breaks so it probably drops locally.

I'll do some more testing when I have time.

**Comment by crow1814** [comment]
Hi, I am trying to verify TSN features on LS1021A-TSN board. Two hosts are connected through the 1021-TSN board, just like fig27 in <OpenILUG_Rev1.9> and they have been synchronized through ptp4l. But I cannot send proper traffic on host1 via ‘isochron send --interface eth0 --dmac 00:04:9f:05:de:06 --priority 6 --vid 0 \ ······’. The ubuntu prompts me that the isochron command is not found. So I would like to ask how to install and use isochron, or how to send traffic with different priorities on host1.

**Comment by vladimiroltean** [comment]
When have you built the OpenIL image, and using what defconfig?
In all defconfigs for the LS1021A-TSN board, the BR2_PACKAGE_QORIQ_TSN_SCRIPTS package is enabled.

**Comment by crow1814** [comment]
I have used the default configuration on 1021-TSN board. I would like to ask how to install and use isochron on host1(ubuntu 16.04).

**Comment by vladimiroltean** [comment]
```
git clone https://github.com/vladimiroltean/tsn-scripts.git
git checkout isochron
make -C isochron
./isochron/isochron --help
```

**Comment by vladimiroltean** [comment]
Hey @jman-88, FWIW I spent some time today and figured out what was the problem. I was right about the source of the problem, but the port flushing procedure was slightly incorrect and therefore didn't work until I fixed it. I unplugged the cable quite a few tens of times now and traffic was still flowing. Sorry it took so long.
