### ISSUE TITLE
802.1CB protocol compliance

### ISSUE THREAD

**Issue by Zhang-Jia** [vladimiroltean/tsn-scripts#10]
Check whether the 802.1CB function of the LS1028A does not comply with 802.1CB 2017 standards.
As shown in the figure below
![e1606dbe68c2225257f1371d99f3bcc](https://user-images.githubusercontent.com/6102202/153373699-fc8daf34-9173-425d-bba3-55435ddd2299.png)

**Comment by vladimiroltean** [comment]
The hardware doesn't comply to 802.1CB-2017:
![Screenshot from 2022-02-10 11-38-20](https://user-images.githubusercontent.com/11811246/153379725-c948338e-20e4-4486-9005-9c562f47ff0e.png)
![Screenshot from 2022-02-10 11-34-42](https://user-images.githubusercontent.com/11811246/153379066-30e26c94-6fc4-47e9-9d01-d22dd737641d.png)
It complies to 802.1CB draft 2.2 (2016):
![Screenshot from 2022-02-10 11-35-50](https://user-images.githubusercontent.com/11811246/153379328-5589985e-8153-492c-aa28-8f9fc9999231.png)
![Screenshot from 2022-02-10 11-39-34](https://user-images.githubusercontent.com/11811246/153379928-fdfe1830-2813-497c-95d3-b026dd948f52.png)

The EtherType can be customized, but the length of the tag can't, and the placement of the Reserved field in the 802.1CB-2017 header format makes them incompatible.

**Comment by Zhang-Jia** [comment]
Thank you for your reply. Can 802.1CB-2017 be configured to remove reserved bits, so as to maintain compatibility with LS1028A.
