### ISSUE TITLE
How to correctly use

### ISSUE THREAD

**Issue by crow1814** [vladimiroltean/tsn-scripts#4]
Hi Vladimir,
I have git clone the whole repository, then I execute "make". However there are some errors here,
`cc  -DVERSION=\"v0.1-00033-gafff3709d5d\"  -c isochron/isochron.c -o isochron/isochron.o
In file included from isochron/isochron.c:8:0:
isochron/isochron.h:11:6: error: unknown type name ‘bool’
      bool omit_sync, bool quiet, bool taprio, bool txtime,
      ^
isochron/isochron.h:11:22: error: unknown type name ‘bool’
      bool omit_sync, bool quiet, bool taprio, bool txtime,
                      ^
isochron/isochron.h:11:34: error: unknown type name ‘bool’
      bool omit_sync, bool quiet, bool taprio, bool txtime,
                                  ^
isochron/isochron.h:11:47: error: unknown type name ‘bool’
      bool omit_sync, bool quiet, bool taprio, bool txtime,
                                               ^
isochron/isochron.h:12:6: error: unknown type name ‘__s64’
      __s64 advance_time);
      ^
isochron/Makefile:14: recipe for target 'isochron/isochron.o' failed
make: *** [isochron/isochron.o] Error 1
`

**Comment by vladimiroltean** [comment]
Solved, thanks.
