### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by crow1814** [vladimiroltean/tsn-scripts#5]
Hi Vladimir,
I have git clone the new repository, then I execute "make". However error still exists,
`
In file included from /usr/include/linux/ipv6.h:6:0,
                 from isochron/send.c:11:
/usr/include/netinet/in.h:101:5: error: expected identifier before numeric const                                                     ant
     IPPROTO_HOPOPTS = 0,   /* IPv6 Hop-by-Hop options.  */
     ^
In file included from isochron/send.c:22:0:
/usr/include/netinet/in.h:211:8: error: redefinition of ‘struct in6_addr’
 struct in6_addr
        ^
In file included from /usr/include/linux/ipv6.h:6:0,
                 from isochron/send.c:11:
/usr/include/linux/in6.h:32:8: note: originally defined here
 struct in6_addr {
        ^
In file included from isochron/send.c:22:0:
/usr/include/netinet/in.h:254:8: error: redefinition of ‘struct sockaddr_in6’
 struct sockaddr_in6
        ^
In file included from /usr/include/linux/ipv6.h:6:0,
                 from isochron/send.c:11:
/usr/include/linux/in6.h:49:8: note: originally defined here
 struct sockaddr_in6 {
        ^
In file included from isochron/send.c:22:0:
/usr/include/netinet/in.h:290:8: error: redefinition of ‘struct ipv6_mreq’
 struct ipv6_mreq
        ^
In file included from /usr/include/linux/ipv6.h:6:0,
                 from isochron/send.c:11:
/usr/include/linux/in6.h:59:8: note: originally defined here
 struct ipv6_mreq {
        ^
isochron/Makefile:14: recipe for target 'isochron/send.o' failed
make: *** [isochron/send.o] Error 1`

**Comment by vladimiroltean** [comment]
Sorry, I cannot reproduce this. Have you tried to "make clean" first? What is the output of "gcc -v"?

**Comment by crow1814** [comment]
I have tried to "make clean" first, but errors still exist.
The output of "gcc -v" is `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)`
In addition, when I execute `make -C isochron`, the output is ` No rule to make target 'isochron/isochron.o', needed by 'isochron/isochron'。`
when I execute `make`, the output are those errors

**Comment by vladimiroltean** [comment]
I did not test with such an old toolchain, sorry. I downloaded gcc 5.4 now and fixed the build error.
